bank2ynab/bank2ynab

transaction_csv_cleanup.py
I have changed the first line from '#! /usr/bin/python' to '#! /usr/bin/python3' instead, to explicitly have my system use the Python version 3. As you expected, that cleared up all of the issues! 
Two questions:
Can we keep 'python3' or does that break anything on your side?
My testing showed that the script stops at line 71 'transaction_data = list(transaction_reader)' if either the file ends with a newline, or the file contains special characters like üöäÜÖÄßæøåÆØÅ. Shouldn't the whole Unicode business already take care of umlauts?
=> changed first line to python3; added screen output.

bank2ynab.py
Issue #25 
Add python version check for csv writing
Also remove delimiter encoding as shouldn't be needed with unicode_literals and was causing me errors -
wasn't working anyway according to @torbengb.
Also move `__future__` to top of file to prevent error.
```
SyntaxError: from __future__ imports must occur at the beginning of the file
TypeError: "delimiter" must be string, not bytes
```
=> Add python version check for csv writing

bank2ynab.py
If running 2.x, import ConfigParser but rename it to configparser. I don't think this should cause any issues with the features we're using of the config parser.
=> Add support for 2.x version of configparser

bank2ynab.conf, bank2ynab.py
Issue #28. Preserves existing memo fields. Only fills in memo field with payee info if memo field is empty. Useful for preserving payee info once renamed in YNAB.
=> Automatically fill empty memo field with payee info

bank2ynab.conf, bank2ynab.py
Remove output about missing directory when no files found in location matching section criteria. Makes for cleaner output. Removed source location from BOI so it will follow default behaviour. 
Issue #48
=> Rearrange get_files function to return better CLI output

bank2ynab.py
New behaviour - now moves rows marked as outflows from inflow column to outflow column instead of making a negative inflow
Fixes #207 - with thanks to @toyg for pointing out the error
=> Change cd_flag_process back to pure text

README.md, bank2ynab.conf
I've added support for: 
- **Arbejdernes Landsbank DK** Verified
- **Merkur Andelskasse DK** Verified
Potentially supported banks due to their membership with BEC (Bankernes EDB Central):
- Nykredit Bank
- Spar Nord
- **[DONE]** Arbejdernes Landsbank     
- Handelsbanken
- VestjyskBANK
- Danske Andelskassers Bank
- Den Jyske Sparekasse
- GrønlandsBANKEN
- Fynske Bank
- Lollands Bank
- Salling Bank
- Lægernes Bank
- Totalbanken
- Møns Bank
- PenSam Bank
- **[DONE]** Merkur Andelskasse
- Hvidbjerg Bank
- Frørup Andelskasse
- Andelskassen Fælleskassen
- Faster Andelskasse
- Frøslev-Mollerup Sparekasse
- Københavns Andelskasse
Testet with the following settings in the export tool:
Date: "whatever you need"
Exportformat: Default (CSV)
"Checkboxes unchecked"
Filename: Blank
=> Added Support for Banks in Denmark with BEC's online banking solution (Arbejdernes Landsbank, merkur andelskasse etc)

README.md, bank2ynab.conf
Adding support for Chase CSV exports
Ran unit-tests locally and everything is passing `python -m unittest discover -v`
=> Add support for US Chase Credit Card

README.md, bank2ynab.conf
Adding support for [Bank of America](https://www.bankofamerica.com) CSV exports.
Bank of America aka (BOFA) doesn't have a separate inflow and outflow column.  Inflow and outflow is represented with a negative or positive number.
Ran unit-tests locally and everything is passing `python -m unittest discover -v`
=> Add support for US Bank of America

bank2ynab.py
Rather than have users specify which Python interpreter via the command line, we can allow the env utility to do this.
If `python3 ./bank2ynab.py` worked for the user, then `./bank2ynab.py` should also work for the user after this change.
[Made a GIF 😬](https://i.imgur.com/BA6duoF.gif)
=> Use env utility in shebang

README.md, bank2ynab.conf, bank2ynab.py
Support for [SK VUB] and required improvements to the infrastructure.
(none)
I am submitting two improvements that are 100% backwards compatible with the existing configuration, but add more flexibility.
1. Dates with leading white space are now allowed. Previously, such dates could not be parsed and would result in exception.
1. Multiple input columns now can be combined to a single output column, by repeating the name of the output column in the *Input columns* configuration:
`Input Columns = Date,skip,Payee,skip,Payee,Inflow,skip,skip,skip,skip,skip,Memo,skip,skip,skip`
1. Both changes were necessary to add support for [SK VUB] which I am submitting as well. The bank in question uses two different Payee columns for bank …
=> softer date parsing, combine multiple input columns, add support for [SK VUB]

bank2ynab.py
none
I had an issue with trailing spaces in dates. (I'm trying to add Revolut Bank)
Example CSV:
```
Completed Date ; Description ; Paid Out (CHF) ; Paid In (CHF) ; Exchange Out; Exchange In; Balance (CHF); Category; Notes
Apr 26, 2019 ; Card Delivery Fee  ; 6.99 ;  ;  ;  ; 3.01; general; 
```
This change solves the issue.
=> Solve issue with trailing spaces in dates

bank2ynab.conf
*#291*
The Deutsche Kreditbank checking account section should be enabled in the config again
I have removed the comments from the Deutsche Kreditbank checking account section and thus enabled it again
=> Re-enable DE Deutsche Kreditbank checking in config

bank2ynab.py
Fixes #293 
As from #293: 
> Transactions with amounts bigger than 999€ get imported without a value
Thanks for flagging the issue, @lukkigi!
Changes fix_decimal_point code (alternative to #294). Replaces every instance of "." in output number except for last instance. Allows for long German-formatted numbers, e.g. 123.567,89 which was previously being processed as 123.567.89. Once the fix_decimal_point function is finished its conversion, we just remove every instance of "." except for the last. That should allow for different arbitrary number separators in future if they occur in different formats and avoids any additional functions.
New fix_decimal_point code for reference:
```
def …
```
=> Fixes #293 number formatting issue

bank2ynab.py
Noticed (after some debugging...) while implementing #328 that only 2 lines would get converter and found an error in the line numbering.
line_num is not equals the rows of the csv. It basically counts \n characters. This fails, when entries contain newlines.
See https://docs.python.org/3.7/library/csv.html#csv.csvreader.line_num
**Changes**
It's a simple and small change, since the csvreader is already used in a for loop. Instead of asking the underlying stream for a line number, just count the loops (the same approach as the lines above for getting the total number of rows).
This fixes especially any issues with line numbering an headers.
=> Fix csvreader line numbering.

bank2ynab.py, requirements.txt
Since chardet is already an indirect dependency (from requests), it can
be easily added for detection. Leaving in the old method as fallback, in
case the confidence is below 50%
I made this change to my sourcecode since the encoding was way off and produced all kinds of artifacts. It's passing the tests, and works for all of my bank accounts in German. They ususally get a confidence level between 0.7 and 0.9
I also added chardet as explicit dependency in requirements.txt
[**chardet**](https://chardet.readthedocs.io/en/latest/index.html)
It's originally code from Mozilla, based on an [interesting paper,](https://www-archive.mozilla.org/projects/intl/universalcharsetdetection) with some fancy algorithms. Since it's used by requests I wouldn't worry too …
=> Add encoding support via chardet.

bank2ynab.conf
Fixes #338
Fixes the export format for Swedish Nordea's old site and adds support for the format exported by the new site.
**Note**
Until #339 is fixed any Nordea SE files exported from the old site with the name of `export.csv` aren't going to work since they'll be overwritten by another (failing) config to be empty files. As a temporary workaround you can rename these to `nordea-export.csv` and they'll be parsed and fixed without conflict.
This is not an issue for exports from the new site, since they're named according to the account you export from and includes the date and time.
=> fix: Nordea SE export formats

bank2ynab.py, plugins/OCBC_Bank_SG.py, plugins/plugin-template.py, test/test_YNAB_API.py
Fixes #339 
As explained in the above issue, if the wrong format is triggered due to a filename mismatch, multiple blank output files are created. This should hopefully rectify this issue.
- Add a line_count check to the read_data function and output only a blank list if it's 0 (or less!)
- Add a check for blank data to the bank processing loop so that blank data is not written anywhere.
=> Add check for empty output data when reading input file

bank2ynab.conf
Fixes #356 
Date Format = %d/%m/%Y 
Input columns = Date,Memo,Inflow,Inflow,skip
#356 
Update to account for four digit year and adjusted input columns according to user feedback. Credit to @zirophyz for the contribution.
=> Change date format and columns for [AU ING]

README.md, bank2ynab.conf
Fixes #122
#122 
Add filename pattern for [US Schwab] and split into separate Checking and Savings accounts.
=> Update US Schwab with default filename pattern

bank2ynab.conf
None
Adds support for the creditcard format used by the Dutch bank Rabobank
=> Add Rabobank creditcard format

bank2ynab.conf
Fixes #365 
Apparently the Dutch bank ING added a new format that changes the delimiter to a semicolon and adds two new (useless) fields.
This adds a new variant of the NL ING checking 2020 entry to support the semicolon-delimited version. The old version is also still available to download on the ING website so I left that in as well.
=> Adds support for new NL ING format

README.md, bank2ynab.conf
Fixes #372 (Partially. No way to differentiate between current account and credit card file as they have the same filename.)
=> Add [SG OCBC Bank Credit Card]

README.md, bank2ynab.conf
Fixes #106 
Adds bank format information provided by @ricardopolo
```
[CO Bancolombia]
Source Filename Pattern = [0-9]{3}-[0-9]{6}-[0-9]{2}_[0-9]{3}
Source Filename Extension = .txt
Use Regex for Filename = True
Source CSV Delimiter = ,
Source Has Column Headers = True
Input Columns = Date,Payee,Memo,Inflow
```
=> Add support for [CO] Bancolombia

bank2ynab.conf
Fixes #397
The latest csv files from Länsförsäkringar contain two-digit year numbers, and that is not recognized by the default. The date format has to be explicitely set in the relevant section in the conf file.
=> Fixing SE Länsförsäkringar checking for two digit year format.

README.md, bank2ynab.conf
No issue open yet
Adds support for the Crypto.com output based on exporting some sample files.
File looks like this:
```
Timestamp (UTC),Transaction Description,Currency,Amount,To Currency,To Amount,Native Currency,Native Amount,Native Amount (in USD),Transaction Kind
2022-01-07 09:12:31,You Need A Budget,USD,-98.99,,,EUR,-87.73,-99.5546152341,
```
=> Add configuration for Crypto.com card CSV export

bank2ynab.conf
Fix for https://github.com/bank2ynab/bank2ynab/pull/410
Seemingly the column order has changed somehow, this is the correct order, example transactions:
```
Timestamp (UTC),Transaction Description,Currency,Amount,To Currency,To Amount,Native Currency,Native Amount,Native Amount (in USD),Transaction Kind
2022-01-07 09:12:31,You Need A Budget,USD,-98.99,,,EUR,-87.73,-99.5546152341,
2022-01-07 09:07:59,Google,EUR,-222.8,,,EUR,-222.8,-252.829913076,
2022-01-07 08:55:51,EUR -> EUR,EUR,750.0,EUR,750.0,EUR,750.0,851.0881275,
```
=> Update Crypto.com column order

bank2ynab/plugins/parse_from_memo.py
Now that `BankHandler.name` is used to decide which account to map to, overriding the name causes problems.
Having the plugin not mutate the name means it falls back to the bank name from the config file and avoids a configparser.NoSectionError when the YNAB upload starts.
Example without this change (note the bank name is **ParseFromMemo** not `BE KBC checking`):
```bash
No YNAB account for transactions from ParseFromMemo set!
Pick an account (range 1 - 2): 1
Traceback (most recent call last):
File "/opt/homebrew/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 197, in _run_module_as_main
return _run_code(code, main_globals, None,
File "/opt/homebrew/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", …
```
=> Plugin ParseFromMemo: Leave bank name as default

.github/workflows/testing.yml, README.md, setup.py
Currently, develop does not run anymore on python 3.6, 3.7 and 3.8, so this should be reflected inside the README.
=> Add the current python version

.github/workflows/label.yml
The label workflow was not able to run in forked repositories to prevent e.g leaking  tokens and don't run untrusted code. 
https://securitylab.github.com/research/github-actions-preventing-pwn-requests/
=> Fix label workflow

bank2ynab.conf
No existing issue.
In the output data for Danske Bank accounts, there is now two new columns, "Kategori" and "Underkatagori".
I've updated the configuration to skip both of these values, so that it can parse the csv and map to the correct columns.
=> fix(bank2ynab.conf): skip new columns for Danske

bank2ynab/dataframe_handler.py
Currently, when multiple inflow or outflow columns are defined, these are incorrectly merged. 
For example:
| Payee  | Inflow | Inflow | Expected merge result |
|--------|--------|--------|-----------------------|
| Github | -30.40 | NaN    | -30.40                |
| Bank   | NaN    | 55.50  | 55.50                 |
I fixed this issue by merging inflow and outflow columns without converting them to strings.
=> Added merging of float columns inflow and outflow

README.md, bank2ynab/dataframe_handler.py, test/unit/test_dataframe_handler.py
Fixes #431 
`dataframe_handler.py`'s `clean_strings` function uses the regex `[^a-zA-Z0-9 ]`, to remove non-alphanumeric characters in strings, but this function replaces all accented characters with spaces.
**Changes**
- Add test case for accented characters to unit tests
- Amend `[^a-zA-Z0-9 ]` to a different regex **(IN PROGRESS)**
=> Allow accented characters in strings (modify clean_strings function)

bank2ynab.conf, bank2ynab/plugins/OCBC_Bank_SG.py
Updates and fixes to handle the latest transaction history exports from OCBC bank in Singapore. 
- Strip single quotes (`'`) from lines as they are being processed by the OCBC plugin
- Update the OCBC import configurations to:
- update the number of header rows for credit cards (there's 7 now)
- also import payees for accounts\
- add a few comments / explanations
=> OCBC: strip quotes, update header rows

bank2ynab.conf
none
In my previous pull request #442, I changed the Source CSV Delimiter for 'CH ZKB Erweiterte Suche' to a comma. As it seems this was a temporary change from the bank.
I had to change the Source CSV Delimiter for 'CH ZKB Erweiterte Suche' back to a semi-colon. Additionally, the bank introduced a new column to the file which can be skipped.
=> Change Source CSV Delimiter back to semi-colon and add an additional row to skip to 'CH ZKB Erweiterte Suche'

bank2ynab.conf
Picked the wrong branch as target in my last pull request. now it should work.
Added German Paypal export format. The downloaded file is always called Download.CSV (capital file type, important for case-sensitive OS). I always rename the files according to the month and day, so I use "[0-9]{6}_Download.CSV", but kept the file name as it is downloaded.
Config changes only
=> added de paypal

bank2ynab.conf
Relates #432 
https://github.com/bank2ynab/bank2ynab/pull/444 added parsing for "DE Deutsche Kreditbank checking new" assuming that the filename would always include "Girokonto" in its name. But users can rename their bank accounts in the webinterface and the custom name is used to name the files. So everything between "Umsatzliste_" and "_DE" is a user controlled string, whitespace characters are replaced with "-" during the export.
=> fix file matching for DE Deutsche Kreditbank checking new

bank2ynab.conf
**Reference Issue:** none
The DKB recently added a new column IBAN to their csv files. Because of this bank2ynab tries to parse the IBAN as inflow which obviously does not make sense. This PR skips the new IBAN column.
The change in the csv column headers is shown below:
```
OLD: "Buchungsdatum";"Wertstellung";"Status";"Zahlungspflichtige*r";"Zahlungsempfänger*in";"Verwendungszweck";"Umsatztyp";       "Betrag";    "Gläubiger-ID";"Mandatsreferenz";"Kundenreferenz"
NEW: "Buchungsdatum";"Wertstellung";"Status";"Zahlungspflichtige*r";"Zahlungsempfänger*in";"Verwendungszweck";"Umsatztyp";"IBAN";"Betrag (€)";"Gläubiger-ID";"Mandatsreferenz";"Kundenreferenz"
```
After merging this bank2ynab will parse older DKB csv files incorrectly. Without it it will not be able to parse newer …
=> skip new IBAN column for DE Deutsche Kreditbank checking new

README.md, bank2ynab/__main__.py, bank2ynab/api_interface.py, bank2ynab/bank_handler.py, bank2ynab/plugins/OCBC_Bank_SG.py, bank2ynab/plugins/fix_line_breaks.py, bank2ynab/plugins/handelsbanken.py, bank2ynab/plugins/null.py, bank2ynab/plugins/parse_from_memo.py, bank2ynab/plugins/pdf_converter.py, bank2ynab/plugins/plugin-template.py, bank2ynab/plugins/xls_converter.py, bank2ynab/ynab_api.py, setup.py
**Reference Issue:** #349 
Please see https://github.com/bank2ynab/bank2ynab/issues/349#issuecomment-2082349551
=> Relative imports and dependency addition
