- README.md
- transaction_csv_cleanup.py
See line 26 for the important change. I omitted the quotechar for now, but to be returned to.
> Merging in the encoding fix.

- README.md
- transaction_csv_cleanup.py
> Encoding fix

- transaction_csv_cleanup.py
I thought I had already done this? Strange, I must have made a mistake. I'll do it again.
> Python3 header

- bank2ynab.py
This doesn't actually work :-(
The part about files_processed seems to work as it should, but the lines about files_converted complains about `UnboundLocalError: local variable 'g_files_converted' referenced before assignment`. Help?
> summary of files processed and converted

- test-data/test.conf
- test/test_B2YBank.py
- test/utils.py
> changed tests to read production conf file first,

- bank2ynab.conf
For #132 I just checked a noticed two separate issues, that are both fixed here.
- 7ecaee2 fixes the credit card data import (and moves the description from the exported CSV to the "memo" section.
- ~~262d432 fixes a general issue with `Header Rows` in combination with `_valid_row` check, I _suspect_  that this is a general issue since the `_valid_row` check is applied before the `Header rows` offset. So `_valid_row` skips some lines and then `Header Rows` will discard some of the valid data~~
> [DE Deutsche Kreditbank] Fix input reading

- README.md
Just to tidy things up a bit! :)
> Can we close the documentation branch?

- bank2ynab.conf
ING DiBa changed their file format:
* Filename: The files are now named `Umsatzanzeige_$IBAN_$Date.csv`.
* Header: There are now 13 rows of headers
* They swapped the columns _Saldo_(balance) and _Betrag_(amount)
> Adjust to new file format of ING DiBa

- .gitignore
- bank2ynab.conf
- bank2ynab.py
Still need to know what the default filename is for sparekassen thy.
Don't know if that qualifies for a pullrequest however.. thanks
Issue reference: #219
> BETA: Added support for sparekassen thy temp filename: thyposteringer

- bank2ynab.conf
(none)
added [SK Tatra Banka] CSV format
this pull request adds a new section to bank2ynab.conf
> added [SK Tatra Banka] CSV format

- user_configuration.conf.template
> Merge conflict fix: renamed user config to template

- bank2ynab.conf
*none*
*I'm adding my Bank (Zürcher Kantonalbank - ZKB). There are two additions. One is for the traditional checking/savings acccount. The other export comes from a view, where you can also include your credit-card bookings into the list.*
> Add ZKB Bank config

- bank2ynab.conf
Adds support for 3 Australian bank exports.
* ANZ (via ANZ.csv)
* ING (via Transactions.csv)
* NAB (via TransactionHistory.csv)
> Add ANZ/NAB/ING Australian banks

- bank2ynab.conf
- Add Payee column header.
- Modify Memo column header. 
The previous Memo column is a redundant copy of multiple columns, but the real Transaction Memo is the last column.
> Correct "BE KBC Checking" Input Columns

- README.md
- bank2ynab.conf
Adds support for BR Banco do Brasil checking account CSV format
> added BR Banco do Brasil checking

- bank2ynab.conf
Tested successfully with download in CSV-CAMT format.
**Reference Issue: #285
Added DE Sparkasse Südholstein
May work for other Sparkasse Banks too
> added DE Sparkasse Südholstein

- bank2ynab.conf
Adds support for Irish version of N26 online bank.
> Add support for IE N26

- README.md
- bank2ynab.conf
Format for the Swedish bank SEB
https://github.com/bank2ynab/bank2ynab/issues/288
> Bankformat for SEB

- README.md
*I wasn't sure if I need to create an issue for a simple README change. If this is needed, I will create one.*
The README did not mention the automatic import and I was quite surprised about that when it works so flawlessly and is definitely a huge feature of the project.
I have added a section to the README mentioning the automatic import and the need for the YNAB API access token.
> Updated the README to mention the automatic import capabilities

- test-data/test.conf
- test/test_JLP_Card.py
Adds unit tests for JLP Card Importer
adds a unit test to make sure that the jlp importer is working
> add unittest for John Lewis Card importer

- README.md
- bank2ynab.conf
- bank2ynab.py
Fixes #231 
Fixes the inability to work with the API due to date formatting issues. Also adds a DEBUG logging level for easier debugging.
Adds a bit of code to change the date format that is provided for the file uploads (mm/dd/yyyy) to the format needed for the API (yyyy-mm-ddd). Also adds the ability to set a `Log Level = DEBUG` for more descriptive debugs
As well: provides more detail in the output about why an API request has failed.
> Feature debug and api fix

- README.md
- bank2ynab.conf
- bank2ynab.py
- plugins/OCBC_Bank_SG.py
- plugins/plugin-template.py
- test/test_YNAB_API.py
> Add most of the format details for [HU OTP] - missing filename details

- bank2ynab.conf
- test-data/export_KBC-Mastercard Business Essential_20200204_1604.csv
- Add config for BE KBC credit card files
- Update the position of the memo field for BE KBC checking files
- Updates `bank2ynab.conf` with a configuration for KBC credit cards
- Adds an example of a KBC credit card file for testing
> Add BE KBC Credit

- bank2ynab.conf
#333 
Current branch parses 0 lines due to a missing date format.
Added the date format to DE ING-DiBa.
> Hotfix#333/DE ING DiBa import fix

- bank2ynab.conf
N/A
Adds support for German Deutsche Bank Credit Card
Added support for German Deutsche Bank Credit Card statement export conversions
> Support for DE Deutsche Bank Credit Card

- bank2ynab.conf
Fixes #131 
Modified/fixed the existing DE Deutsche Bank
Added correct Filename pattern, corrected header rows, corrected Input Column and added the correct date format
> DE Deutsche Bank Support added

- README.md
- bank_list_update.py
#239 (doesn't fix the issue but creates a helper script that may be leveraged in the future)
Adds bank_list_update.py, which can be run to pull the list of banks from bank2ynab.conf and update README.md's list accordingly.
> Add bank list updater for README.md that uses list from bank2ynab.conf

- .gitignore
- README.md
- bank2ynab.conf
No related issue.
Added USAA format.
> Adding USAA format

- bank2ynab.conf
Added LV Swedbank configuration
Sample CSV:
```csv
"Klienta konts";"Ieraksta tips";"Datums";"Saņēmējs/Maksātājs";"Informācija saņēmējam";"Summa";"Valūta";"Debets/Kredīts";"Arhīva kods";"Maksājuma veids";"Refernces numurs";"Dokumenta numurs";
"xxxxxx";"10";"01.10.2020";"";"Sākuma atlikums";"10000,00";"EUR";"K";"";"AS";"";"";
"xxxxxx";"20";"05.10.2020";"John Doe";"Memo";"6,20";"EUR";"D";"xxxxx";"IZP";"";"";
"xxxxxx";"82";"31.10.2020";"";"Apgrozījums";"0,00";"EUR";"D";"";"K2";"";"";
"xxxxxx";"82";"31.10.2020";"";"Apgrozījums";"6,20";"EUR";"K";"";"K2";"";"";
"xxxxxx";"86";"31.10.2020";"";"Beigu atlikums";"10000,00";"EUR";"K";"";"LS";"";"";
```
> feat: add LV Swedbank configuration

- README.md
- bank2ynab.conf
Fixes #360 
Adds updated config for Swedbank.
```
[SE Swedbank 2020]
Use Regex For Filename = True
Source Filename Pattern = Transaktioner_20([0-9]{2}-){2}[0-9]{2}_([0-9]{2}-){2}[0-9]{2}
Header Rows = 2
Input Columns = skip,skip,skip,skip,skip,Date,skip,skip,Payee,Memo,Inflow,skip
Date Format = %Y-%m-%d
```
> Add bank config for Swedbank 2020

- bank2ynab.conf
Update input columns. Fixes #373
> Update HU OTP format

- README.md
- bank2ynab.conf
#95
Added Denmarks largest bank, Danske Bank, to `bank2ynab.conf` and `README.md`.
Added DK Danske bank
> Added DK Danske Bank

- bank2ynab.conf
> Issue #384 Rename to Portalbank

- bank2ynab.conf
#392
Added bank format for HU K&H
> Added HU K&H bank format, closes #392

- bank2ynab.conf
Feature Request for new bank
- Full name of the bank: Amazon Kredikarten Banking LBB
- Country (2-character country code): DE
- Any special requirements: Needed to swap Inflow with Outflow
- Testfile: [KKB-Umsätze_20210830_2354.csv](https://github.com/bank2ynab/bank2ynab/files/7449525/KKB-Umsatze_20210830_2354.csv)
Implemented the feature request :)
> Support for DE Amazon VISA LBB

- README.md
- bank2ynab.conf
Added Swiss bank UBS, both for checking accounts and credit card statements.
> Added CH UBS bank

- README.md
- bank2ynab.conf
Hey friends,
I am almost surprised this is not covered yet. Adding Hibiscus, a quite good open source cross-platform banking software: https://www.willuhn.de/products/hibiscus/
This PR covers its default export format.
> Add Hibiscus as supported csv source

- bank2ynab/ynab_api.py
A quick fix to make the script a bit more chatty. Imho definitely an area this great piece of code can have a bit more of ;)
> Add YNAB imported vs skipped metrics

- README.md
- bank2ynab.conf
- bank2ynab/plugins/pdf_converter.py
> Catch up with develop

- bank2ynab.conf
```python
>>> mystr = "Umsätze_"
>>> [(ch, ord(ch)) for ch in mystr]
[('U', 85), ('m', 109), ('s', 115), ('ä', 228), ('t', 116), ('z', 122), ('e', 101), ('_', 95)]
>>> mystr = "Umsätze_"
>>> [(ch, ord(ch)) for ch in mystr]
[('U', 85), ('m', 109), ('s', 115), ('a', 97), ('̈', 776), ('t', 116), ('z', 122), ('e', 101), ('_', 95)]
```
> Amazon VISA lBB

- .github/workflows/codestyle.yml
- .github/workflows/testing.yml
- bank2ynab/__main__.py
- bank2ynab/api_interface.py
- bank2ynab/bank_handler.py
- bank2ynab/dataframe_handler.py
- bank2ynab/plugins/OCBC_Bank_SG.py
- bank2ynab/plugins/handelsbanken.py
- bank2ynab/plugins/null.py
- bank2ynab/plugins/parse_from_memo.py
- bank2ynab/plugins/pdf_converter.py
- bank2ynab/plugins/plugin-template.py
- bank2ynab/transactionfile_reader.py
- bank2ynab/ynab_api.py
- pyproject.toml
- requirements-dev.txt
- setup.py
- test/integration/utils.py
- test/unit/test_dataframe_handler.py
Run more linters on GitHub actions and fixed their output.
> Linting work

- bank2ynab.conf
#425 
Provides support for new John Lewis Partnership cards issued by NewDay
Adds a new bank format
Renames the old JL Partnership card format
> Update to include new JL Partnership card format

- README.md
- bank2ynab.conf
*Type # followed by the issue number this pull request pertains to*
I've added support for SwissCard bank.
And I've added support for new csv format for checking accounts from UBS.
> Add support for two Swiss banks

- bank2ynab.conf
No existing issue.
The output .csv for SE Länsförsäkringar has changed. The columns for "Kontonummer";"Kontonamn";"";"Saldo";"Tillgängligt belopp" is now in the header, which also results in 4 Header Rows instead of 1. The Date Format has also changed and is now %Y-%m-%d instead %d/%m/%y.
Also "Transaktionstyp" should be used as Memo instead of skipped.
I have updated the bank2ynab.conf to reflect these changes.
> Updated .csv for SE Länsförsäkringar

- .github/PULL_REQUEST_TEMPLATE.md
- .github/workflows/codestyle.yml
- README.md
- bank2ynab/dataframe_handler.py
Fixes #436 
Linting action is failing see #436 for details.
Update Black Github Action settings to those recommended by Black. This **removes** the automatic fixing of formatting errors, unfortunately, but this wasn't working for merges from forks anyway, so this is actually a good thing. This way we know if there's a failing Lint test, it's genuine.
> Update Linting action

- README.md
- bank2ynab.conf
**Reference Issue:** #439 
New format for PL Alior Bank. 
Ran it locally for few export from different types of account (personal, savings and business types)
> Add PL Alior Bank format

- bank2ynab.conf
*Type # followed by the issue number this pull request pertains to*
- none
*Note that any submitted code must conform to the standards set by the Black linter. Please review the automated Linting test results on the pull request after saving and make any required changes or the submitted code will not be accepted.*
- ZKB changed the CSV file one can export. The new CSV delimiter is now a comma instead of a semi-colon.
> Change Source CSV Delimiter for "CH ZKB Erweiterte Suche" to comma ","

- bank2ynab.conf
Fixes #432 
DKB has a new online banking that has a different csv export format. It probably makes sense to keep the old format in for a while. They don't conflict as the file naming is different.
Only configuration changes
> add DE Deutsche Kreditbank checking new

- README.md
- bank2ynab.conf
- bank2ynab/plugins/fix_line_breaks.py
Fixes #135 
Add conf entry and create plugin to handle weird linebreaks.
> Add support for [BR Banco Bradesco Checking]

- bank2ynab.conf
This pull request introduces new configurations for the Neon Bank and Wise Bank in the bank2ynab.conf file. These changes allow the application to correctly parse and process CSV files for these specific account statements.
The patch adds a new configuration block for the CH Neon Monthly Account Statement, which includes a regex pattern for the filename, header rows, input columns, date format, and CSV delimiter. Additionally, it modifies the existing CH SwissCard section to correct the input columns and adds a new configuration for Wise with its own source filename pattern, header rows, input columns, and date format.
The changes ensure that the bank2ynab tool can now handle CSV files from CH Neon …
> Add CH Neon Monthly Account Statement and Wise Configurations

- bank2ynab.conf
Fixes #452
More specific regex to catch only BE BNP Paribas Fortis CSV files
More specific regex to catch only BE BNP Paribas Fortis CSV files
> Update BE BNP Paribas Fortis config to avoid match with NL Rabobank

- README.md
- bank2ynab.conf
- bank2ynab/__main__.py
- bank2ynab/bank_handler.py
- bank2ynab/config_handler.py
- bank2ynab/ynab_api.py
Fixes #455
This adds a flag to determine if the output file should be saved. This is useful when availing of the YNAB API integration as saving a fixed statement may not be desirable.
> Add "Save Output File" flag to config file

- bank2ynab/__main__.py
- bank2ynab/api_interface.py
- bank2ynab/bank_handler.py
- bank2ynab/plugins/OCBC_Bank_SG.py
- bank2ynab/plugins/fix_line_breaks.py
- bank2ynab/plugins/handelsbanken.py
- bank2ynab/plugins/null.py
- bank2ynab/plugins/parse_from_memo.py
- bank2ynab/plugins/pdf_converter.py
- bank2ynab/plugins/plugin-template.py
- bank2ynab/plugins/xls_converter.py
- bank2ynab/ynab_api.py
- setup.py
**Reference Issue:** #349 
*Type # followed by the issue number this pull request pertains to*
Please see https://github.com/bank2ynab/bank2ynab/issues/349#issuecomment-2082349551
*Note that any submitted code must conform to the standards set by the Black linter. Please review the automated Linting test results on the pull request after saving and make any required changes or the submitted code will not be accepted.*
> PyPI packaging
